### PR TITLE
ci: fix tools

### PR DESCRIPTION
**Pull request by hanny21**
# Checklist

- [ ] `make test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](./doc/guides/commit-message.md#commit-message-guidelines)

### CODE REVIEW

**Comment by bakkelim** [comment]
What is wrong with tools? 🙂

**Comment by arxeiss** [comment]
@bakkelim  We were missing some in `tools.go` so for new developer it was impossible to run generate proto, run linter etc

**Comment by bakkelim** [comment]
@arxeiss Was it related to Mac? Because I ran `make install-tools` on a mac yesterday and gci did not get installed

**Review by bakkelim — APPROVED** [review]

**Comment by arxeiss** [comment]
Not sure. It always worked for me, because those tools were installed from `jarvis-proto` already. But Hanka came on clean computer (not Mac :green_apple: , but Linux :penguin: ) and those tools were missing for her.

**Pull request merged**
